server:
  port: 5001

logging:
  file:
    name: logs/app.log

spring:
  application:
    name: payment-gateway
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/payments?authSource=admin

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
