server:
  port: 5002

logging:
  file:
    name: logs/app.log


spring:
  application:
    name: payments-query
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/payments?createDatabaseIfNotExists=true
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    listener:
      ack-node: MANUAL
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentsConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
